---
deployment:
    tasks:
        - export DEPLOYPATH=/home/fspfaqiv/public_html/
        - /bin/cp index.html $DEPLOYPATH
        - /bin/cp style.css $DEPLOYPATH
        - /bin/cp script.js $DEPLOYPATH
        - /bin/cp script-layanan.js $DEPLOYPATH
        - /bin/cp -R images $DEPLOYPATH
        - /bin/cp -R layanan-kami $DEPLOYPATH
        - /bin/cp -R en $DEPLOYPATH
