---
deployment:
    tasks:
        - export DEPLOYPATH=/home/fspfaqiv/public_html/
        - /bin/cp index.html $DEPLOYPATH
        # - /bin/cp style.css $DEPLOYPATH
        # - /bin/cp script.js $DEPLOYPATH
        # - /bin/cp -R css $DEPLOYPATH
        # - /bin/cp -R js $DEPLOYPATH
        - /bin/cp -R images $DEPLOYPATH
